# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 21:33
from __future__ import unicode_literals

import apps.roundtable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundtable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[(apps.roundtable.models.Ratings(2), 2), (apps.roundtable.models.Ratings(1), 1), (apps.roundtable.models.Ratings(0), 0), (apps.roundtable.models.Ratings(-1), -1), (apps.roundtable.models.Ratings(-5), -5)], default=apps.roundtable.models.Ratings(0), max_length=5),
        ),
    ]
