# Generated by Django 2.1.7 on 2019-02-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roundtable', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
