# Generated by Django 2.1.7 on 2019-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundtable', '0002_auto_20190227_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
